# Site settings
title: David Mazza
email: davidedwardmazza@gmail.com
description: "I am an engineer. I write Ruby, Objective-C and this."
baseurl: ""
url: "http://davidmazza.com"
twitter_username: dmzza
github_username:  dmzza

# Build settings
markdown: kramdown
permalink: pretty
