# Site settings
title: David&nbsp;Mazza
email: davidedwardmazza@gmail.com
brand_values: "I simplify new ideas and turn them into apps."
description: "I write Swift, Objective-C and this."
baseurl: ""
category_dir: ""
url: "http://davidmazza.com"
twitter_username: dmzza
github_username:  dmzza

# Build settings
markdown: kramdown
permalink: pretty
